name: sfsnet-pt
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0=0
  - pip=21.0.1
  - python=3.6.13
  - pytorch-cpu=1.0.0=py3.6_cpu_1
  - torchvision-cpu=0.2.1=py_2
  - pip:
    - dlib==19.16.0
    - h5py==2.9.0
    - matplotlib==2.2.3
    - numpy==1.16.6
    - opencv-python==3.4.13.47


